import Head from 'next/head';
import Image from 'next/image';
import Avatar from '../components/avatar/Avatar';

import { ViewGridIcon , MicrophoneIcon } from "@heroicons/react/solid";
import {  SearchIcon } from "@heroicons/react/outline";
export default function Home() {
  return (
    <div >
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <header className="flex w-full p-5 justify-between text-sm text-gray-700">
         <div className="flex space-x-4 items-center">
           <p className="link">About</p>
           <p className="link">Store</p>
         </div>

         <div className="flex space-x-4 items-center">
           <p className="link">Gmail</p>
           <p className="link">Images</p>

            <ViewGridIcon  className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer"/>
           <Avatar url="https://coaching.papareact.com/ai9"/>
         </div>
         
     </header>
      
     <form>

       <Image
         src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
         width={300}
         height={100}
       />

       <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg">
           <SearchIcon
             className="h-5 mr-3 text-gray-500 "
           />
           <input
             type="text"
             className="focus:outline-none"
           />
           <MicrophoneIcon className="h-5"/>
       </div>
     </form>

       
    </div>
  )
}
