import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <header>
         <div className="flex space-x-4">
           <p>About</p>
           <p>Store</p>
         </div>

         <div>
           <p>Gmail</p>
           <p>Images</p>
         </div>
     </header>
      
    </div>
  )
}
